DROP TABLE IF EXISTS contato;
CREATE TABLE contato (
id_contato INT AUTO_INCREMENT,
nome VARCHAR(100) NOT NULL,
telefone VARCHAR(50) NOT NULL,
email VARCHAR(50) NOT NULL,
dt_criacao TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
dt_atualizacao TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
status BOOLEAN DEFAULT true
);